import asyncio
import json
from pathlib import Path

import pytest

from concrete_console.shade_provider.shade import ShadeClient, ShadeError


def run(awaitable):
    return asyncio.run(awaitable)


def write_fake_uv(path: Path, *, shade_dir: Path, log_path: Path, fail: bool = False, bad_policy: bool = False) -> None:
    script = f"""#!/usr/bin/env python3
import json
import os
import stat
import sys
from pathlib import Path

LOG_PATH = Path({json.dumps(str(log_path))})
SHADE_DIR = {json.dumps(str(shade_dir))}
args = sys.argv[1:]
entry = {{"args": args, "leaked_secret": "CONCRETE_SHOULD_NOT_LEAK" in os.environ}}

if {str(fail)}:
    print("shade failed", file=sys.stderr)
    LOG_PATH.write_text(json.dumps(entry) + "\\n", encoding="utf-8")
    sys.exit(7)

if args[:4] != ["run", "--project", SHADE_DIR, "shade"]:
    print(f"unexpected args: {{args}}", file=sys.stderr)
    sys.exit(2)

cmd = args[4:]
if cmd[:1] == ["build"]:
    config_path = Path(cmd[cmd.index("-c") + 1])
    compose_path = Path(cmd[cmd.index("-f") + 1])
    output_path = Path(cmd[cmd.index("-o") + 1])
    entry["config_mode"] = oct(stat.S_IMODE(config_path.stat().st_mode))
    entry["compose_mode"] = oct(stat.S_IMODE(compose_path.stat().st_mode))
    entry["config_text"] = config_path.read_text(encoding="utf-8")
    entry["compose_text"] = compose_path.read_text(encoding="utf-8")
    output_path.write_text("# Generated by Shade Framework\\nservices:\\n  app:\\n    image: example/app@sha256:abc\\n", encoding="utf-8")
    print(f"Generated {{output_path}}")
elif cmd[:2] == ["policy", "generate"]:
    compose_path = Path(cmd[cmd.index("--compose") + 1])
    output_path = Path(cmd[cmd.index("--output") + 1])
    entry["compose_text"] = compose_path.read_text(encoding="utf-8")
    if {str(bad_policy)}:
        output_path.write_text("[1, 2, 3]", encoding="utf-8")
    else:
        output_path.write_text(json.dumps({{"type": "dstack_tdx", "allowed_tcb_status": ["UpToDate"]}}), encoding="utf-8")
    print(f"Wrote {{output_path}}")
else:
    print(f"unexpected shade command: {{cmd}}", file=sys.stderr)
    sys.exit(3)

with LOG_PATH.open("a", encoding="utf-8") as handle:
    handle.write(json.dumps(entry) + "\\n")
"""
    path.write_text(script, encoding="utf-8")
    path.chmod(0o700)


def read_log(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()]


def test_build_invokes_shade_build_with_private_staging(monkeypatch, tmp_path: Path) -> None:
    shade_dir = tmp_path / "shade"
    shade_dir.mkdir()
    log_path = tmp_path / "uv.log"
    uv_path = tmp_path / "uv"
    write_fake_uv(uv_path, shade_dir=shade_dir, log_path=log_path)
    monkeypatch.setenv("CONCRETE_SHOULD_NOT_LEAK", "secret")

    client = ShadeClient(shade_dir=shade_dir, uv_bin=str(uv_path))
    result = run(
        client.build(
            shade_config_yaml="app:\n  name: app\ncvm:\n  domain: cvm.example.com\n",
            app_compose_yaml="services:\n  app:\n    image: example/app@sha256:abc\n",
        )
    )

    assert "Generated by Shade Framework" in result.compose_yaml
    entry = read_log(log_path)[0]
    assert entry["args"][:5] == ["run", "--project", str(shade_dir), "shade", "build"]
    assert entry["config_mode"] == "0o600"
    assert entry["compose_mode"] == "0o600"
    assert entry["leaked_secret"] is False


def test_generate_policy_invokes_shade_policy_generate(tmp_path: Path) -> None:
    shade_dir = tmp_path / "shade"
    shade_dir.mkdir()
    log_path = tmp_path / "uv.log"
    uv_path = tmp_path / "uv"
    write_fake_uv(uv_path, shade_dir=shade_dir, log_path=log_path)

    client = ShadeClient(shade_dir=shade_dir, uv_bin=str(uv_path))
    result = run(
        client.generate_policy(
            domain="cvm.example.com",
            connect_host="app-443s.dstack.example.com",
            deploy_compose_yaml="services:\n  app:\n    image: example/app@sha256:abc\n",
        )
    )

    assert result.policy == {"type": "dstack_tdx", "allowed_tcb_status": ["UpToDate"]}
    entry = read_log(log_path)[0]
    assert entry["args"][:6] == ["run", "--project", str(shade_dir), "shade", "policy", "generate"]
    assert "--allowed-tcb-status" in entry["args"]
    assert entry["args"][entry["args"].index("--connect-host") + 1] == "app-443s.dstack.example.com"


def test_build_with_policy_uses_generated_compose(tmp_path: Path) -> None:
    shade_dir = tmp_path / "shade"
    shade_dir.mkdir()
    log_path = tmp_path / "uv.log"
    uv_path = tmp_path / "uv"
    write_fake_uv(uv_path, shade_dir=shade_dir, log_path=log_path)

    client = ShadeClient(shade_dir=shade_dir, uv_bin=str(uv_path))
    result = run(
        client.build_with_policy(
            shade_config_yaml="app:\n  name: app\ncvm:\n  domain: cvm.example.com\n",
            app_compose_yaml="services:\n  app:\n    image: example/app@sha256:abc\n",
            domain="cvm.example.com",
        )
    )

    assert result.policy["type"] == "dstack_tdx"
    build_entry, policy_entry = read_log(log_path)
    assert "Generated by Shade Framework" in policy_entry["compose_text"]
    assert build_entry["args"][4] == "build"


def test_cli_failure_raises_shade_error(tmp_path: Path) -> None:
    shade_dir = tmp_path / "shade"
    shade_dir.mkdir()
    uv_path = tmp_path / "uv"
    write_fake_uv(uv_path, shade_dir=shade_dir, log_path=tmp_path / "uv.log", fail=True)

    client = ShadeClient(shade_dir=shade_dir, uv_bin=str(uv_path))

    with pytest.raises(ShadeError) as exc:
        run(client.build(shade_config_yaml="app:\n  name: app\n", app_compose_yaml="services: {}\n"))

    assert exc.value.code == "cli_failed"
    assert "shade failed" in exc.value.output


def test_from_settings_requires_existing_shade_dir(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.delenv("SHADE_DIR", raising=False)
    with pytest.raises(ShadeError) as exc:
        ShadeClient.from_settings()
    assert exc.value.code == "not_configured"

    monkeypatch.setenv("SHADE_DIR", str(tmp_path / "missing"))
    with pytest.raises(ShadeError) as exc:
        ShadeClient.from_settings()
    assert exc.value.code == "invalid_shade_dir"

    shade_dir = tmp_path / "shade"
    shade_dir.mkdir()
    monkeypatch.setenv("SHADE_DIR", str(shade_dir))
    assert ShadeClient.from_settings().shade_dir == shade_dir


def test_invalid_policy_output_is_rejected(tmp_path: Path) -> None:
    shade_dir = tmp_path / "shade"
    shade_dir.mkdir()
    uv_path = tmp_path / "uv"
    write_fake_uv(uv_path, shade_dir=shade_dir, log_path=tmp_path / "uv.log", bad_policy=True)

    client = ShadeClient(shade_dir=shade_dir, uv_bin=str(uv_path))

    with pytest.raises(ShadeError) as exc:
        run(client.generate_policy(domain="cvm.example.com", deploy_compose_yaml="services: {}\n"))

    assert exc.value.code == "invalid_policy"
