[workspace]
resolver = "2"
members = ["cli", "cvms/dev/user-sandbox/atls-connect"]

[workspace.package]
version = "0.3.0-beta.3"
edition = "2021"
authors = ["Concrete Security maintainers"]
license-file = "LICENSE.txt"
repository = "https://github.com/concrete-security/concrete"
homepage = "https://github.com/concrete-security/concrete"
documentation = "https://github.com/concrete-security/concrete/tree/main/docs"
rust-version = "1.92"
keywords = ["confidential-computing", "developer-tools", "security", "cli"]
categories = ["command-line-utilities", "development-tools"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.cli-install]
inherits = "release"
lto = false
codegen-units = 16
