{
 "title": "Machine - Metrics Overview",
 "refresh": "1s",
 "panels": [
  {
   "title": "Running vs Waiting requests: Server load and saturation over time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    { "expr": "vllm:num_requests_running", "legendFormat": "Running (req/s)" },
    { "expr": "vllm:num_requests_waiting", "legendFormat": "Waiting (req/s)" },
    {
     "expr": "vllm:num_requests_running + vllm:num_requests_waiting",
     "legendFormat": "Total (req/s)"
    }
   ]
  },
  {
   "title": "Success requests per 30s: Server load and saturation over time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "sum(rate(vllm:request_success_total[30s]))",
     "legendFormat": "Success (req/s)"
    }
   ]
  },
  {
   "title": "KeyValue Cache Usage (%): KV saturation → risk of preemptions",
   "type": "timeseries",
   "description": "The KV Cache is the GPU memory used to store Key and Value vectors during token generation.\nvLLM uses the KV cache to speed up generation.\nIf this memory is insufficient → the system must eject requests = preemptions",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "avg(vllm:kv_cache_usage_perc)", "legendFormat": "KV Cache (%)" }
   ]
  },
  {
   "title": "GPU Preemptions / sec: If > 0: eviction or throttling → GPU fully saturated",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "rate(vllm:num_preemptions_total[1m])",
     "legendFormat": "Preemptions/s"
    }
   ]
  },
  {
   "title": "The average number of cores used by vLLM: Overall CPU load",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 27, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Prefix Cache: nb times vLLM checks if it can reuse a previously calculated prefix Vs nb times vLLM actually finds a previously calculated prefix / sec",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 36, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "rate(vllm:prefix_cache_hits_total[1m])",
     "legendFormat": "nb times vllm checks prefix cache / s"
    },
    {
     "expr": "rate(vllm:prefix_cache_queries_total[1m])",
     "legendFormat": "nb times vllm finds prefix cache / s"
    }
   ]
  },
  {
   "title": "% of queries that find a prefix that has already been seen",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 45, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100*(sum(rate(vllm:prefix_cache_hits_total[1m])) / clamp_min(sum(rate(vllm:prefix_cache_queries_total[1m])),1))",
     "legendFormat": "Hit-Rate"
    }
   ]
  },
  {
   "title": "Process Resident Memory Bytes: The total size of the virtual memory space requested by the process at time T.",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 54, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" }
   ]
  }
 ]
}