#!/usr/bin/env bash
# Build a generated .env file by merging the four required layers for MODE.
#
# Rules:
# - MODE must be one of: dev, staging, prod
# - Exactly four layers are required
# - A variable may appear in one layer only
# - Existing .env is replaced only when generated content changes
# - When an existing .env changes, a backup is created as:
#     .env.bak.<MODE>.<YYYYMMDD>.<HHMMSS>
#
# Usage:
#   make build-env MODE=staging
#   MODE=staging ./ops/host/build-env.sh
#   ./ops/host/build-env.sh staging

set -euo pipefail

MODE="${1:-${MODE:-}}"
OUT="${ENV_FILE_OUT:-.env}"

merged_tmp=""
final_tmp=""

log() {
  echo "build-env: $*" >&2
}

die() {
  log "$@"
  exit 1
}

validate_mode() {
  case "$MODE" in
    dev|staging|prod)
      ;;
    "")
      die "set MODE=<dev|staging|prod>, e.g. 'make build-env MODE=staging'"
      ;;
    *)
      die "invalid MODE='${MODE}' (expected: dev | staging | prod)"
      ;;
  esac
}

require_layers() {
  local missing=0

  for layer in "$@"; do
    if [ ! -f "$layer" ]; then
      log "missing required layer '${layer}'"
      missing=1
    fi
  done

  if [ "$missing" -ne 0 ]; then
    die "all four layers are required for MODE=${MODE}"
  fi
}

merge_layers() {
  local output="$1"
  shift

  # NOTE: keep every printf() on a single line. The default awk on Debian/Ubuntu
  # (mawk) does not allow a function call's argument list to span multiple lines
  # ("missing ) near end of line"); only gawk tolerates that.
  awk -F= '
    /^[[:space:]]*#/ || /^[[:space:]]*$/ {
      next
    }

    /^[A-Za-z_][A-Za-z0-9_]*=/ {
      key = $1

      if (key == "GHCR_USER" || key == "GHCR_TOKEN" || key == "GH_TOKEN") {
        printf("build-env: publish-only credential %s must be supplied to the invoking process, not persisted in %s\n", key, FILENAME) > "/dev/stderr"
        invalid = 1
        next
      }

      if (key in source) {
        printf("build-env: duplicate key %s in both %s and %s\n", key, source[key], FILENAME) > "/dev/stderr"
        duplicate = 1
        next
      }

      source[key] = FILENAME
      order[++count] = key

      sub(/^[^=]*=/, "")
      value[key] = $0

      next
    }

    /^[[:space:]]*export[[:space:]]/ {
      printf("build-env: invalid variable declaration with '\''export'\'' at %s:%d (drop the '\''export'\'' prefix)\n", FILENAME, FNR) > "/dev/stderr"
      invalid = 1
      next
    }

    {
      printf("build-env: invalid .env syntax at %s:%d\n", FILENAME, FNR) > "/dev/stderr"
      invalid = 1
    }

    END {
      if (duplicate || invalid) {
        exit 3
      }

      for (i = 1; i <= count; i++) {
        key = order[i]
        print key "=" value[key]
      }
    }
  ' "$@" > "$output"
}

write_final_file() {
  local merged_file="$1"
  local final_file="$2"
  shift 2

  {
    echo "# GENERATED by 'make build-env MODE=${MODE}' from: $*"
    echo "# Do not edit directly; edit the layer files and re-run. (.env is gitignored)"
    cat "$merged_file"
  } > "$final_file"
}

main() {
  validate_mode

  local layers=(
    ".env.common"
    ".env.${MODE}"
    ".env.admin"
    ".env.${MODE}.secrets"
  )

  require_layers "${layers[@]}"

  log "merging: ${layers[*]}"

  merged_tmp="$(mktemp)"
  final_tmp="$(mktemp)"

  trap 'rm -f "$merged_tmp" "$final_tmp"' EXIT

  if ! merge_layers "$merged_tmp" "${layers[@]}"; then
    die "aborted — each runtime variable must be defined in exactly one layer, publish credentials must stay out of the merged environment, and every line must be valid"
  fi

  local var_count
  var_count="$(grep -c '^[A-Za-z_][A-Za-z0-9_]*=' "$merged_tmp" || true)"

  log "no duplicate variables (${var_count} merged)"

  write_final_file "$merged_tmp" "$final_tmp" "${layers[@]}"

  if [ -f "$OUT" ] && cmp -s "$final_tmp" "$OUT"; then
    log "${OUT} already up to date for MODE=${MODE} (${var_count} variables) — no change, no backup"
    exit 0
  fi

  local backup=""

  if [ -f "$OUT" ]; then
    backup="${OUT}.bak.${MODE}.$(date +%Y%m%d.%H%M%S)"
    cp "$OUT" "$backup"
  fi

  mv "$final_tmp" "$OUT"

  log "created ${OUT} for MODE=${MODE} (${var_count} variables merged) — success"

  if [ -n "$backup" ]; then
    log "previous ${OUT} changed — backed up to ${backup}"
  fi
}

main "$@"
